name: Vuego CLI automation

jobs:
  default:
    steps:
      - task: fmt
      - task: lint
      - task: test

  fmt:
    desc: "Format the code"
    steps:
      - splint fix ./...
      - go mod tidy

  test:
    passthru: true
    steps:
      - gotestsum ./... -- -count 1
      - go-fsck docs . > docs/api.md

  lint:
    passthru: true
    steps:
      - splint ./...
